using System.Diagnostics;
using System.Globalization;

namespace create_measurements;

public class WeatherStation(string city, double meanTemperature)
{
    private static readonly IEnumerator<double> Rng = NextGaussianEnumerator();
    public readonly string City = city;

    public double Measurement() => Math.Round(meanTemperature + NextGaussian() * 10.0, 1);

    private static double NextGaussian()
    {
        Rng.MoveNext();
        return Rng.Current;
    }

    private static IEnumerator<double> NextGaussianEnumerator()
    {
        while (true)
        {
            var rnd = System.Random.Shared;
            double v1, v2, s;
            do
            {
                v1 = 2 * rnd.NextDouble() - 1;   // between -1.0 and 1.0
                v2 = 2 * rnd.NextDouble() - 1;   // between -1.0 and 1.0
                s = v1 * v1 + v2 * v2;
            } while (s is >= 1 or 0);
            var multiplier = Math.Sqrt(-2 * Math.Log(s) / s);
            yield return v1 * multiplier;
            yield return v2 * multiplier;
        }
    }

    private static readonly WeatherStation[] All =
        {
            new("Abha", 18.0),
            new("Abidjan", 26.0),
            new("Abéché", 29.4),
            new("Accra", 26.4),
            new("Addis Ababa", 16.0),
            new("Adelaide", 17.3),
            new("Aden", 29.1),
            new("Ahvaz", 25.4),
            new("Albuquerque", 14.0),
            new("Alexandra", 11.0),
            new("Alexandria", 20.0),
            new("Algiers", 18.2),
            new("Alice Springs", 21.0),
            new("Almaty", 10.0),
            new("Amsterdam", 10.2),
            new("Anadyr", -6.9),
            new("Anchorage", 2.8),
            new("Andorra la Vella", 9.8),
            new("Ankara", 12.0),
            new("Antananarivo", 17.9),
            new("Antsiranana", 25.2),
            new("Arkhangelsk", 1.3),
            new("Ashgabat", 17.1),
            new("Asmara", 15.6),
            new("Assab", 30.5),
            new("Astana", 3.5),
            new("Athens", 19.2),
            new("Atlanta", 17.0),
            new("Auckland", 15.2),
            new("Austin", 20.7),
            new("Baghdad", 22.77),
            new("Baguio", 19.5),
            new("Baku", 15.1),
            new("Baltimore", 13.1),
            new("Bamako", 27.8),
            new("Bangkok", 28.6),
            new("Bangui", 26.0),
            new("Banjul", 26.0),
            new("Barcelona", 18.2),
            new("Bata", 25.1),
            new("Batumi", 14.0),
            new("Beijing", 12.9),
            new("Beirut", 20.9),
            new("Belgrade", 12.5),
            new("Belize City", 26.7),
            new("Benghazi", 19.9),
            new("Bergen", 7.7),
            new("Berlin", 10.3),
            new("Bilbao", 14.7),
            new("Birao", 26.5),
            new("Bishkek", 11.3),
            new("Bissau", 27.0),
            new("Blantyre", 22.2),
            new("Bloemfontein", 15.6),
            new("Boise", 11.4),
            new("Bordeaux", 14.2),
            new("Bosaso", 30.0),
            new("Boston", 10.9),
            new("Bouaké", 26.0),
            new("Bratislava", 10.5),
            new("Brazzaville", 25.0),
            new("Bridgetown", 27.0),
            new("Brisbane", 21.4),
            new("Brussels", 10.5),
            new("Bucharest", 10.8),
            new("Budapest", 11.3),
            new("Bujumbura", 23.8),
            new("Bulawayo", 18.9),
            new("Burnie", 13.1),
            new("Busan", 15.0),
            new("Cabo San Lucas", 23.9),
            new("Cairns", 25.0),
            new("Cairo", 21.4),
            new("Calgary", 4.4),
            new("Canberra", 13.1),
            new("Cape Town", 16.2),
            new("Changsha", 17.4),
            new("Charlotte", 16.1),
            new("Chiang Mai", 25.8),
            new("Chicago", 9.8),
            new("Chihuahua", 18.6),
            new("Chișinău", 10.2),
            new("Chittagong", 25.9),
            new("Chongqing", 18.6),
            new("Christchurch", 12.2),
            new("City of San Marino", 11.8),
            new("Colombo", 27.4),
            new("Columbus", 11.7),
            new("Conakry", 26.4),
            new("Copenhagen", 9.1),
            new("Cotonou", 27.2),
            new("Cracow", 9.3),
            new("Da Lat", 17.9),
            new("Da Nang", 25.8),
            new("Dakar", 24.0),
            new("Dallas", 19.0),
            new("Damascus", 17.0),
            new("Dampier", 26.4),
            new("Dar es Salaam", 25.8),
            new("Darwin", 27.6),
            new("Denpasar", 23.7),
            new("Denver", 10.4),
            new("Detroit", 10.0),
            new("Dhaka", 25.9),
            new("Dikson", -11.1),
            new("Dili", 26.6),
            new("Djibouti", 29.9),
            new("Dodoma", 22.7),
            new("Dolisie", 24.0),
            new("Douala", 26.7),
            new("Dubai", 26.9),
            new("Dublin", 9.8),
            new("Dunedin", 11.1),
            new("Durban", 20.6),
            new("Dushanbe", 14.7),
            new("Edinburgh", 9.3),
            new("Edmonton", 4.2),
            new("El Paso", 18.1),
            new("Entebbe", 21.0),
            new("Erbil", 19.5),
            new("Erzurum", 5.1),
            new("Fairbanks", -2.3),
            new("Fianarantsoa", 17.9),
            new("Flores,  Petén", 26.4),
            new("Frankfurt", 10.6),
            new("Fresno", 17.9),
            new("Fukuoka", 17.0),
            new("Gabès", 19.5),
            new("Gaborone", 21.0),
            new("Gagnoa", 26.0),
            new("Gangtok", 15.2),
            new("Garissa", 29.3),
            new("Garoua", 28.3),
            new("George Town", 27.9),
            new("Ghanzi", 21.4),
            new("Gjoa Haven", -14.4),
            new("Guadalajara", 20.9),
            new("Guangzhou", 22.4),
            new("Guatemala City", 20.4),
            new("Halifax", 7.5),
            new("Hamburg", 9.7),
            new("Hamilton", 13.8),
            new("Hanga Roa", 20.5),
            new("Hanoi", 23.6),
            new("Harare", 18.4),
            new("Harbin", 5.0),
            new("Hargeisa", 21.7),
            new("Hat Yai", 27.0),
            new("Havana", 25.2),
            new("Helsinki", 5.9),
            new("Heraklion", 18.9),
            new("Hiroshima", 16.3),
            new("Ho Chi Minh City", 27.4),
            new("Hobart", 12.7),
            new("Hong Kong", 23.3),
            new("Honiara", 26.5),
            new("Honolulu", 25.4),
            new("Houston", 20.8),
            new("Ifrane", 11.4),
            new("Indianapolis", 11.8),
            new("Iqaluit", -9.3),
            new("Irkutsk", 1.0),
            new("Istanbul", 13.9),
            new("İzmir", 17.9),
            new("Jacksonville", 20.3),
            new("Jakarta", 26.7),
            new("Jayapura", 27.0),
            new("Jerusalem", 18.3),
            new("Johannesburg", 15.5),
            new("Jos", 22.8),
            new("Juba", 27.8),
            new("Kabul", 12.1),
            new("Kampala", 20.0),
            new("Kandi", 27.7),
            new("Kankan", 26.5),
            new("Kano", 26.4),
            new("Kansas City", 12.5),
            new("Karachi", 26.0),
            new("Karonga", 24.4),
            new("Kathmandu", 18.3),
            new("Khartoum", 29.9),
            new("Kingston", 27.4),
            new("Kinshasa", 25.3),
            new("Kolkata", 26.7),
            new("Kuala Lumpur", 27.3),
            new("Kumasi", 26.0),
            new("Kunming", 15.7),
            new("Kuopio", 3.4),
            new("Kuwait City", 25.7),
            new("Kyiv", 8.4),
            new("Kyoto", 15.8),
            new("La Ceiba", 26.2),
            new("La Paz", 23.7),
            new("Lagos", 26.8),
            new("Lahore", 24.3),
            new("Lake Havasu City", 23.7),
            new("Lake Tekapo", 8.7),
            new("Las Palmas de Gran Canaria", 21.2),
            new("Las Vegas", 20.3),
            new("Launceston", 13.1),
            new("Lhasa", 7.6),
            new("Libreville", 25.9),
            new("Lisbon", 17.5),
            new("Livingstone", 21.8),
            new("Ljubljana", 10.9),
            new("Lodwar", 29.3),
            new("Lomé", 26.9),
            new("London", 11.3),
            new("Los Angeles", 18.6),
            new("Louisville", 13.9),
            new("Luanda", 25.8),
            new("Lubumbashi", 20.8),
            new("Lusaka", 19.9),
            new("Luxembourg City", 9.3),
            new("Lviv", 7.8),
            new("Lyon", 12.5),
            new("Madrid", 15.0),
            new("Mahajanga", 26.3),
            new("Makassar", 26.7),
            new("Makurdi", 26.0),
            new("Malabo", 26.3),
            new("Malé", 28.0),
            new("Managua", 27.3),
            new("Manama", 26.5),
            new("Mandalay", 28.0),
            new("Mango", 28.1),
            new("Manila", 28.4),
            new("Maputo", 22.8),
            new("Marrakesh", 19.6),
            new("Marseille", 15.8),
            new("Maun", 22.4),
            new("Medan", 26.5),
            new("Mek'ele", 22.7),
            new("Melbourne", 15.1),
            new("Memphis", 17.2),
            new("Mexicali", 23.1),
            new("Mexico City", 17.5),
            new("Miami", 24.9),
            new("Milan", 13.0),
            new("Milwaukee", 8.9),
            new("Minneapolis", 7.8),
            new("Minsk", 6.7),
            new("Mogadishu", 27.1),
            new("Mombasa", 26.3),
            new("Monaco", 16.4),
            new("Moncton", 6.1),
            new("Monterrey", 22.3),
            new("Montreal", 6.8),
            new("Moscow", 5.8),
            new("Mumbai", 27.1),
            new("Murmansk", 0.6),
            new("Muscat", 28.0),
            new("Mzuzu", 17.7),
            new("N'Djamena", 28.3),
            new("Naha", 23.1),
            new("Nairobi", 17.8),
            new("Nakhon Ratchasima", 27.3),
            new("Napier", 14.6),
            new("Napoli", 15.9),
            new("Nashville", 15.4),
            new("Nassau", 24.6),
            new("Ndola", 20.3),
            new("New Delhi", 25.0),
            new("New Orleans", 20.7),
            new("New York City", 12.9),
            new("Ngaoundéré", 22.0),
            new("Niamey", 29.3),
            new("Nicosia", 19.7),
            new("Niigata", 13.9),
            new("Nouadhibou", 21.3),
            new("Nouakchott", 25.7),
            new("Novosibirsk", 1.7),
            new("Nuuk", -1.4),
            new("Odesa", 10.7),
            new("Odienné", 26.0),
            new("Oklahoma City", 15.9),
            new("Omaha", 10.6),
            new("Oranjestad", 28.1),
            new("Oslo", 5.7),
            new("Ottawa", 6.6),
            new("Ouagadougou", 28.3),
            new("Ouahigouya", 28.6),
            new("Ouarzazate", 18.9),
            new("Oulu", 2.7),
            new("Palembang", 27.3),
            new("Palermo", 18.5),
            new("Palm Springs", 24.5),
            new("Palmerston North", 13.2),
            new("Panama City", 28.0),
            new("Parakou", 26.8),
            new("Paris", 12.3),
            new("Perth", 18.7),
            new("Petropavlovsk-Kamchatsky", 1.9),
            new("Philadelphia", 13.2),
            new("Phnom Penh", 28.3),
            new("Phoenix", 23.9),
            new("Pittsburgh", 10.8),
            new("Podgorica", 15.3),
            new("Pointe-Noire", 26.1),
            new("Pontianak", 27.7),
            new("Port Moresby", 26.9),
            new("Port Sudan", 28.4),
            new("Port Vila", 24.3),
            new("Port-Gentil", 26.0),
            new("Portland (OR)", 12.4),
            new("Porto", 15.7),
            new("Prague", 8.4),
            new("Praia", 24.4),
            new("Pretoria", 18.2),
            new("Pyongyang", 10.8),
            new("Rabat", 17.2),
            new("Rangpur", 24.4),
            new("Reggane", 28.3),
            new("Reykjavík", 4.3),
            new("Riga", 6.2),
            new("Riyadh", 26.0),
            new("Rome", 15.2),
            new("Roseau", 26.2),
            new("Rostov-on-Don", 9.9),
            new("Sacramento", 16.3),
            new("Saint Petersburg", 5.8),
            new("Saint-Pierre", 5.7),
            new("Salt Lake City", 11.6),
            new("San Antonio", 20.8),
            new("San Diego", 17.8),
            new("San Francisco", 14.6),
            new("San Jose", 16.4),
            new("San José", 22.6),
            new("San Juan", 27.2),
            new("San Salvador", 23.1),
            new("Sana'a", 20.0),
            new("Santo Domingo", 25.9),
            new("Sapporo", 8.9),
            new("Sarajevo", 10.1),
            new("Saskatoon", 3.3),
            new("Seattle", 11.3),
            new("Ségou", 28.0),
            new("Seoul", 12.5),
            new("Seville", 19.2),
            new("Shanghai", 16.7),
            new("Singapore", 27.0),
            new("Skopje", 12.4),
            new("Sochi", 14.2),
            new("Sofia", 10.6),
            new("Sokoto", 28.0),
            new("Split", 16.1),
            new("St. John's", 5.0),
            new("St. Louis", 13.9),
            new("Stockholm", 6.6),
            new("Surabaya", 27.1),
            new("Suva", 25.6),
            new("Suwałki", 7.2),
            new("Sydney", 17.7),
            new("Tabora", 23.0),
            new("Tabriz", 12.6),
            new("Taipei", 23.0),
            new("Tallinn", 6.4),
            new("Tamale", 27.9),
            new("Tamanrasset", 21.7),
            new("Tampa", 22.9),
            new("Tashkent", 14.8),
            new("Tauranga", 14.8),
            new("Tbilisi", 12.9),
            new("Tegucigalpa", 21.7),
            new("Tehran", 17.0),
            new("Tel Aviv", 20.0),
            new("Thessaloniki", 16.0),
            new("Thiès", 24.0),
            new("Tijuana", 17.8),
            new("Timbuktu", 28.0),
            new("Tirana", 15.2),
            new("Toamasina", 23.4),
            new("Tokyo", 15.4),
            new("Toliara", 24.1),
            new("Toluca", 12.4),
            new("Toronto", 9.4),
            new("Tripoli", 20.0),
            new("Tromsø", 2.9),
            new("Tucson", 20.9),
            new("Tunis", 18.4),
            new("Ulaanbaatar", -0.4),
            new("Upington", 20.4),
            new("Ürümqi", 7.4),
            new("Vaduz", 10.1),
            new("Valencia", 18.3),
            new("Valletta", 18.8),
            new("Vancouver", 10.4),
            new("Veracruz", 25.4),
            new("Vienna", 10.4),
            new("Vientiane", 25.9),
            new("Villahermosa", 27.1),
            new("Vilnius", 6.0),
            new("Virginia Beach", 15.8),
            new("Vladivostok", 4.9),
            new("Warsaw", 8.5),
            new("Washington, D.C.", 14.6),
            new("Wau", 27.8),
            new("Wellington", 12.9),
            new("Whitehorse", -0.1),
            new("Wichita", 13.9),
            new("Willemstad", 28.0),
            new("Winnipeg", 3.0),
            new("Wrocław", 9.6),
            new("Xi'an", 14.1),
            new("Yakutsk", -8.8),
            new("Yangon", 27.5),
            new("Yaoundé", 23.8),
            new("Yellowknife", -4.3),
            new("Yerevan", 12.4),
            new("Yinchuan", 9.0),
            new("Zagreb", 10.7),
            new("Zanzibar City", 26.0),
            new("Zürich", 9.3)
    };

    public static WeatherStation Random() => All[System.Random.Shared.Next(0, All.Length - 1)];
}

public class CreateMeasurements
{
    public static async Task<int> Main(string[] args)
    {
        var size = int.Parse(args[0]);
        var watch = Stopwatch.StartNew();

        await using var writer = new StreamWriter("measurements.txt", false, System.Text.Encoding.UTF8, 512 * 1024);
        for (var i = 0; i < size; i++)
        {
            if (i > 0 && i % 50_000_000 == 0)
            {
                Console.WriteLine($"Wrote {i} measurements in {watch.ElapsedMilliseconds} ms");
            }
            var station = WeatherStation.Random();
            await writer.WriteAsync(station.City);
            await writer.WriteAsync(';');
            await writer.WriteLineAsync(station.Measurement().ToString(CultureInfo.InvariantCulture));
        }

        return 0;
    }
}